POST https://localhost:7159/api/Booking
Content-Type: application/json
{
  "userId": 3,
  "roomType": "Single",
  "checkInDate": "2026-06-01T00:00:00Z",
  "checkOutDate": "2026-06-05T00:00:00Z"
}dotnet ef database update
